GET http:localhost:8000/

###
GET http://localhost:8000/api

###
POST http://localhost:3000/signup
Content-Type: "application/json"

{
    "name":"rahul",
    "username":"raj",
    "password":"12345"
}

###
GET http://localhost:3000